# This file was generated by GoReleaser. DO NOT EDIT.
class Kubecredcache < Formula
  desc "kubecredcache makes kubectl run faster by caching the AWS EKS token"
  homepage "https://github.com/jamesdobson/kubecredcache"
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jamesdobson/kubecredcache/releases/download/v1.0.1/kubecredcache_1.0.1_macOS_x86_64.tar.gz"
    sha256 "e8ccae3e76a38bede5e95ea18f99b87dd208214ccca8a8d2bffec795cba2857d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jamesdobson/kubecredcache/releases/download/v1.0.1/kubecredcache_1.0.1_Linux_x86_64.tar.gz"
      sha256 "748a743fc77b193a4c3a35c455ac684210fbb0f22054899edf9cd178bb03563c"
    end
  end

  def install
    bin.install "kubecredcache"
  end
end
